# .github/workflows/main.yml

name: CI/CD Pipeline to AWS EC2

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECR_IMAGE_TAG: latest
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # ================= CI (Build & Push) =================
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        IMAGE_URI: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.ECR_IMAGE_TAG }}
      run: |
        docker build -t $ECR_REPOSITORY .
        docker tag $ECR_REPOSITORY $IMAGE_URI
        docker push $IMAGE_URI

    # ================= CD (Terraform IaC) =================
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.0.0 # Specify a version if needed

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ./infrastructure

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -no-color -input=false \
          -var="ecr_image_uri=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.ECR_IMAGE_TAG }}" \
          -var="aws_region=${{ env.AWS_REGION }}" \
#          -var="ecr_registry_uri=${{ secrets.ECR_REGISTRY }}"
      working-directory: ./infrastructure

    - name: Terraform Apply
      id: apply
      # Only deploy if there are changes to the infrastructure plan
      if: steps.plan.outcome == 'success'
      run: |
        terraform apply -auto-approve \
          -var="ecr_image_uri=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.ECR_IMAGE_TAG }}" \
          -var="aws_region=${{ env.AWS_REGION }}" \
          -var="ecr_registry_uri=${{ secrets.ECR_REGISTRY }}"
      working-directory: ./infrastructure